### ISSUE TITLE
 código do aplicativo

### ISSUE THREAD

**Issue by ajatsoft** [murilosandiego/flutter-delivery-app#1]
Moito obrigado

**Comment by murilosandiego** [comment]
@ajatsoft, blz?
Você tem que iniciar o backend (https://strapi.io/). As instruções estão no Readme. 

Qualquer dúvida de como iniciar é só falar.

**Comment by murilosandiego** [comment]
@ajatsoft, encontrei essa playlist no youtube, talvez possa te ajudar a entender como funciona o Strapi. https://www.youtube.com/watch?v=9GAl1nlNcbo&list=PLtluGZbI5ESiFrDDnKmwJNdrKZKI-hECj
